name: test-and-build

on:
  push:
    branches: ['*']
    tags: ['v*']

  schedule:
    # Periodically test against current Go version
    - cron: '23 4 * * 0'

permissions:
  contents: read

jobs:
  test-and-build:
    defaults:
      run:
        shell: bash

    runs-on: forgejo

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run coverage-tests
        run: go test -v -race -cover ./...

      - name: Check code for linter errors
        run: golangci-lint run ./...

      - name: Run Trivy check
        run: |
          trivy fs . \
            --dependency-tree \
            --exit-code 1 \
            --format table \
            --ignore-unfixed \
            --quiet \
            --scanners license,misconfig,secret,vuln \
            --severity HIGH,CRITICAL
