name: test-and-build

on:
  push:
    branches: ['*']
    tags: ['v*']

  schedule:
    # Periodically test against current Go version
    - cron: '23 4 * * 0'

permissions:
  contents: read

jobs:
  test-and-build:
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/luzifer-docker/action-env:master@sha256:a69ffc884f0bfbb2fa4398fb186e5a7efcb41e056064780b50bd459bdf249dba
      env:
        CGO_ENABLED: 1
        GOPATH: /go

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Marking workdir safe
        run: git config --global --add safe.directory /__w/rconfig/rconfig

      - name: Run coverage-tests
        run: go test -v -race -cover ./...

      - name: Check code for linter errors
        run: golangci-lint run ./...

      - name: Run Trivy check
        run: |
          trivy fs . \
            --dependency-tree \
            --exit-code 1 \
            --format table \
            --ignore-unfixed \
            --quiet \
            --scanners license,misconfig,secret,vuln \
            --severity HIGH,CRITICAL
