name: test-and-build

on:
  push:
    branches: ['*']
    tags: ['v*']

  schedule:
    # Periodically test against current Go version
    - cron: '23 4 * * 0'

permissions:
  contents: read

jobs:
  test-and-build:
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/luzifer-docker/action-env:master@sha256:f8c005c3a87d4987e40e371f152f4fedaba449bce7f060589c13250366b7eef6
      env:
        CGO_ENABLED: 1
        GOPATH: /go

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Marking workdir safe
        run: git config --global --add safe.directory /__w/rconfig/rconfig

      - name: Run coverage-tests
        run: go test -v -race -cover ./...

      - name: Check code for linter errors
        run: golangci-lint run ./...

      - name: Run Trivy check
        run: |
          trivy fs . \
            --dependency-tree \
            --exit-code 1 \
            --format table \
            --ignore-unfixed \
            --quiet \
            --scanners license,misconfig,secret,vuln \
            --severity HIGH,CRITICAL
