name: test-and-build

on:
  push:
    branches: ['*']
    tags: ['v*']

  schedule:
    # Periodically test against current Go version
    - cron: '23 4 * * 0'

permissions:
  contents: read

jobs:
  test-and-build:
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/luzifer-docker/action-env:master@sha256:2539b418c38b69856f9f0a34de0110b6fb23dc425cf1ddcb3f00add2ca5f916c
      env:
        CGO_ENABLED: 1
        GOPATH: /go

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Marking workdir safe
        run: git config --global --add safe.directory /__w/rconfig/rconfig

      - name: Run coverage-tests
        run: go test -v -race -cover ./...

      - name: Check code for linter errors
        run: golangci-lint run ./...

      - name: Run Trivy check
        run: |
          trivy fs . \
            --dependency-tree \
            --exit-code 1 \
            --format table \
            --ignore-unfixed \
            --quiet \
            --scanners license,misconfig,secret,vuln \
            --severity HIGH,CRITICAL
